
function toggleMenu(btn){const menu=document.getElementById('nav-menu');if(!menu)return;const open=menu.classList.toggle('open');btn.setAttribute('aria-expanded',String(open));btn.setAttribute('aria-label',open?'メニューを閉じる':'メニューを開く');}
function escRegExp(s){return s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&');}
function linkify(text){let s=text.replace(/(doi:)(10\.\d{4,9}\/[\-._;()/:A-Za-z0-9]+)/gi,(_,p,d)=>`${p}<a href="https://doi.org/${d}" target="_blank" rel="noopener noreferrer">${d}</a>`);s=s.replace(/(北地雄|Kitaji Y)/g,'<mark>$1</mark>');return s;}
const labels={journal:['査読付き学術誌論文','Peer-reviewed journal articles'],reviews:['総説・解説・教育論文等','Reviews / educational articles'],proceedings:['査読付き国際会議Proceedings','Peer-reviewed conference proceedings'],invited:['招待・教育・企画講演','Invited / educational talks'],international:['国際学会発表','International conference presentations'],domestic:['国内学会発表','Domestic conference presentations']};
function section(key,items){const sec=document.createElement('section');sec.className='pub-section';sec.dataset.category=key;const [jp,en]=labels[key];sec.innerHTML=`<header class="pub-section-head"><div><h2>${jp}</h2><div class="micro">${en}</div></div><span class="count">${items.length}件${key==='proceedings'?' · 国際発表と重複':''}</span></header><div class="pub-list"></div>`;const list=sec.querySelector('.pub-list');if(key==='domestic'){let y=null;items.forEach(item=>{if(item.year!==y){const head=document.createElement('div');head.className='year-group';head.textContent=item.year;y=item.year;list.appendChild(head);}list.appendChild(entry(key,item));});}else{items.forEach(item=>list.appendChild(entry(key,item)));}return sec;}
function entry(key,item){const el=document.createElement('article');el.className='pub-item';el.dataset.search=(item.text+' '+(item.year||'')).toLowerCase();el.innerHTML=`<time class="pub-year">${item.year||''}</time><div class="pub-text">${linkify(item.text)}</div>`;return el;}
function renderPublications(){const root=document.getElementById('publication-root');if(!root||!window.CV_DATA)return;['journal','reviews','proceedings','invited','international','domestic'].forEach(k=>root.appendChild(section(k,window.CV_DATA[k])));setupFilters();}
function setupFilters(){const q=document.getElementById('pub-search');const filters=[...document.querySelectorAll('.filter,.metric')];let cat='all';function apply(){const query=(q?.value||'').toLowerCase().trim();let shown=0;document.querySelectorAll('.pub-section').forEach(sec=>{const sectionOK=cat==='all'||sec.dataset.category===cat;let local=0;sec.querySelectorAll('.pub-item').forEach(item=>{const ok=sectionOK&&(!query||item.dataset.search.includes(query));item.style.display=ok?'':'none';if(ok){shown++;local++;}});sec.querySelectorAll('.year-group').forEach(g=>{let n=g.nextElementSibling,visible=false;while(n&&!n.classList.contains('year-group')){if(n.classList.contains('pub-item')&&n.style.display!=='none')visible=true;n=n.nextElementSibling;}g.style.display=visible?'':'none';});sec.style.display=sectionOK&&local>0?'':'none';});document.querySelector('.empty').style.display=shown?'none':'block';}
if(q)q.addEventListener('input',apply);filters.forEach(b=>b.addEventListener('click',()=>{cat=b.dataset.cat;filters.forEach(x=>x.classList.toggle('active',x.dataset.cat===cat));apply();if(b.classList.contains('metric'))document.querySelector('.pub-layout')?.scrollIntoView({behavior:'smooth',block:'start'});}));}
document.addEventListener('DOMContentLoaded',renderPublications);
